import { useCallback, useEffect, useState } from 'react'
import { ImageIcon, ThumbsUp, MessageCircle, Share2 } from 'lucide-react'
import { getCampaignCreative, CampaignControlError, type CreativePreview } from '@/lib/meta/campaignApi'
import ModalShell from './ModalShell'
import type { Campaign } from '../types'

interface Props {
  campaign: Campaign
  onClose: () => void
}

/** Renders the AI-generated creative from the launch draft the way it would
 * appear on Facebook. Campaigns that were manually briefed (no AI draft
 * behind them) don't have a stored creative to show — that's a real state,
 * not an error, so it's handled with an honest empty state rather than a
 * fabricated preview. */
export default function PreviewAdModal({ campaign, onClose }: Props) {
  const [data, setData] = useState<CreativePreview | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const fetchCreative = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      setData(await getCampaignCreative(campaign.id))
    } catch (err) {
      setError(err instanceof CampaignControlError ? err.message : 'Could not load this campaign\'s creative.')
    } finally {
      setLoading(false)
    }
  }, [campaign.id])

  useEffect(() => { fetchCreative() }, [fetchCreative])

  return (
    <ModalShell title="Preview ad" subtitle={campaign.name} onClose={onClose}>
      {loading ? (
        <div className="h-64 bg-white/5 rounded-xl animate-pulse" />
      ) : error ? (
        <div className="text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-2.5">{error}</div>
      ) : !data?.available || !data.creative ? (
        <div className="text-center py-10">
          <ImageIcon size={28} className="text-slate-700 mx-auto mb-3" />
          <p className="text-slate-400 text-sm">No stored creative for this campaign</p>
          <p className="text-slate-600 text-xs mt-1">
            {data?.reason ?? 'This campaign was set up as a manual brief, not generated by the AI Manager.'}
          </p>
        </div>
      ) : (
        <div className="bg-white rounded-xl overflow-hidden border border-white/10">
          {/* Facebook-style ad card */}
          <div className="px-4 py-3 flex items-center gap-2.5 border-b border-slate-100">
            <div className="w-8 h-8 rounded-full bg-brand-600 flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
              {campaign.name.charAt(0).toUpperCase()}
            </div>
            <div className="min-w-0">
              <p className="text-slate-900 text-sm font-semibold truncate">{campaign.name}</p>
              <p className="text-slate-500 text-[11px]">Sponsored</p>
            </div>
          </div>
          <div className="px-4 py-3">
            <p className="text-slate-800 text-sm leading-relaxed">{data.creative.primary_text}</p>
          </div>
          <div className="aspect-video bg-slate-100 flex items-center justify-center">
            <ImageIcon size={32} className="text-slate-300" />
          </div>
          <div className="px-4 py-3 flex items-center justify-between bg-slate-50">
            <p className="text-slate-900 text-sm font-semibold truncate pr-3">{data.creative.headline}</p>
            <span className="flex-shrink-0 text-xs font-semibold text-slate-700 border border-slate-300 rounded-md px-3 py-1.5 whitespace-nowrap">
              {data.creative.cta}
            </span>
          </div>
          <div className="px-4 py-2 flex items-center gap-4 border-t border-slate-100 text-slate-500 text-xs">
            <span className="flex items-center gap-1"><ThumbsUp size={12} /> Like</span>
            <span className="flex items-center gap-1"><MessageCircle size={12} /> Comment</span>
            <span className="flex items-center gap-1"><Share2 size={12} /> Share</span>
          </div>
        </div>
      )}
    </ModalShell>
  )
}
