import React, { useState, useEffect } from 'react';
import { Globe, Plus, Sparkles, ExternalLink, Edit, RefreshCw } from 'lucide-react';
import { apiRequest } from '@/lib/api';

export const LandingPages: React.FC = () => {
  const [pages, setPages] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadLandingPages();
  }, []);

  const loadLandingPages = async () => {
    setLoading(true);
    try {
      const data: any = await apiRequest('/landing/pages');
      setPages(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleCreatePage = async () => {
    try {
      const newPage: any = await apiRequest('/landing/create', {
        method: 'POST',
        body: JSON.stringify({
          template_id: 'tpl_ecom_v2',
          title: 'Candle Craft — Special Offer Page',
        }),
      });
      setPages((prev) => [newPage, ...prev]);
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Landing Pages</h1>
          <p className="text-sm text-slate-400">High-converting landing pages auto-generated by AI from admin templates</p>
        </div>

        <button
          onClick={handleCreatePage}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold shadow-lg shadow-blue-500/20"
        >
          <Plus className="w-4 h-4" />
          <span>New AI Landing Page</span>
        </button>
      </div>

      {loading ? (
        <div className="flex justify-center py-12 text-slate-500">
          <RefreshCw className="w-6 h-6 animate-spin" />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {pages.map((p) => (
            <div key={p.id} className="p-5 rounded-2xl bg-[#12121A] border border-white/10 space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-3 rounded-xl bg-purple-500/10 border border-purple-500/20 text-purple-400">
                  <Globe className="w-5 h-5" />
                </div>
                <div className="overflow-hidden">
                  <h3 className="font-bold text-white text-sm truncate">{p.title}</h3>
                  <span className="text-xs text-slate-400">Template: {p.template_id}</span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2 text-center p-3 rounded-xl bg-slate-900 border border-white/5 text-xs">
                <div>
                  <span className="text-[10px] text-slate-400 uppercase">Views</span>
                  <p className="font-bold text-white">{p.views}</p>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400 uppercase">Leads / Conv.</span>
                  <p className="font-bold text-emerald-400">{p.submissions}</p>
                </div>
              </div>

              <div className="flex items-center justify-between pt-2 text-xs">
                <a
                  href={p.hosted_url}
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-1 text-blue-400 hover:underline"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>Visit Hosted URL</span>
                </a>
                <button className="flex items-center gap-1 text-slate-300 hover:text-white">
                  <Edit className="w-3.5 h-3.5" />
                  <span>Edit HTML</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
